Be better about exit/return code in bootstrap

diff --git a/bin/bootstrap b/bin/bootstrap
--- a/bin/bootstrap
+++ b/bin/bootstrap
@@ -19,32 +19,48 @@ epoch() {
 
 lib::bash::lib-install() {
   local __home=$(pwd)
-  [[ -d "${LibBash__GitDestinationFolder}" ]] || git clone ${LibBash__GitUrl} ${LibBash__GitDestinationFolder} 2>&1 | cat > /dev/null
+
+  [[ -d "${LibBash__GitDestinationFolder}" ]] || \
+    git clone ${LibBash__GitUrl} ${LibBash__GitDestinationFolder} 2>&1 | cat > /dev/null
+
   [[ -z ${CI} && -d "${LibBash__GitDestinationFolder}" ]] && {
+
     cd ${LibBash__GitDestinationFolder}
     if [[ ${LibBash__LastRebaseAt} -gt 0 ]]; then
+
       local now=$(epoch)
       local sinceLast=$((${now} - ${LibBash__LastRebaseAt}))
+
       if [[ ${sinceLast} -gt ${LibBash__RebaseEvery} ]]; then
+        printf "⇨ ${bldblu}lib-bash may be outdated, updating...${txtgrn}\n" >&2
+
         export LibBash__LastRebaseAt=${now}
-        printf "⇨ ${bldblu}lib-bash may be outdated, updating...${clr}\n" >&2
         git pull --rebase 2>/dev/null 1>/dev/null
         code=$?
-        if [[ ${code} == 128 ]]; then
-          printf "${bldylw}Warning: unable to do ${bldblu}git pull --rebase${bldylw} inside ../lib-bash${clr}\n"
-          printf "Do you have local changes there? Please check ${bldylw}../lib-bash${clr} folder.\n"
-          exit ${code}
-        elif [[ ${code} != 0 ]]; then
-          printf "${bldylw}Warning: unable to do ${bldblu}git pull --rebase${bldylw} inside ../lib-bash${clr}\n"
-          printf "Exit code is ${code}\n"
-          exit ${code}
+
+        if [[ ${code} != 0 ]]; then
+          if [[ ${code} == 128 ]]; then
+            printf "${bldylw}Warning: unable to do ${bldblu}git pull --rebase${bldylw}\n" \
+                   "inside ${bldgrn}${LibBash__GitDestinationFolder}${clr}\n" >&2
+            printf "Do you have local changes there? Please check ${bldylw}../lib-bash${clr} " \
+                   "folder.\n" >&2
+          else
+            printf "${bldylw}Warning: unable to do ${bldblu}git pull --rebase${bldylw} " \
+                   "inside ${bldgrn}${LibBash__GitDestinationFolder}${clr}\n" >&2
+            printf "Exit code is ${code}\n" >&2
+          fi
+          (( $_s_ )) && return ${code} || exit ${code}
         fi
       fi
     fi
   }
 
   cd ${__home} 1>/dev/null
-  [[ -L "${LibBash__InstallationFolder}" ]] || ln -nfs ../${LibBash__GitDestinationFolder}/lib/ ${LibBash__InstallationFolder} 2>&1 | cat > /dev/null
+
+  [[ -L "${LibBash__InstallationFolder}" ]] || \
+     ln -nfs ../${LibBash__GitDestinationFolder}/lib/ ${LibBash__InstallationFolder} 2>&1 | cat > /dev/null
+
+  return
 }
 
 lib::bash::gitignore() {
@@ -59,6 +75,7 @@ lib::bash::gitignore() {
   done
 }
 
-lib::bash::lib-install
-lib::bash::gitignore
-lib::bash::source ${LibBash__InstallationFolder}
+lib::bash::lib-install && \
+  lib::bash::gitignore && \
+  lib::bash::source ${LibBash__InstallationFolder}
+
